name: cars
description: GoMechanic-like MVP

# Flutter SDK version
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Fonts
  google_fonts: ^6.2.1

  # Date/time utilities
  intl: ^0.19.0

  # State management
  provider: ^6.1.2

  # Unique IDs
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "D:/flutter/cars/assets/icons/icon.png"
flutter:
  uses-material-design: true

  # Declare assets
  assets:
    - assets/images/
    - assets/data/services.json
