name: cars
description: GoMechanic-like MVP

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  google_maps_flutter: ^2.3.0
  geolocator: ^12.0.0 
  http: ^1.1.0
  firebase_messaging: ^14.6.7
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  uuid: ^4.4.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cupertino_icons: ^1.0.8
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "D:/flutter/cars/assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/services.json
